package: project_manager_plus
version: '2.0.0-dev'
author: 'Friends Of REDAXO, Alexander Walther'
supportpage: https://github.com/alexplusde/project_manager_plus

page:
    title: Projekt Manager Plus
    perm: admin
    icon: rex-icon fa-handshake-o
    
    subpages:
        main:
            title: 'translate:project_manager_plus_main'
            perm: admin
            icon: rex-icon fa-info    
            itemclass: pull-right 
        client:
            title: 'translate:project_manager_plus_client'
            perm: admin
            icon: rex-icon fa-wrench
        server_overview:
            title: 'translate:project_manager_plus_server_overview'
            perm: admin
            icon: rex-icon fa-wrench
        server_projects:
            title: 'translate:project_manager_plus_server_project_detail'
            perm: admin
            icon: rex-icon fa-wrench
        server_config:
            title: 'translate:project_manager_plus_server_config'
            perm: admin
            icon: rex-icon fa-wrench
        hosting:
            title: translate:project_manager_plus_hosting_title
        pagespeed_overview:
            title: 'translate:project_manager_plus_pagespeed_title'
        pagespeed_config:
            title: 'translate:project_manager_plus_pagespeed_config'

requires:
    packages:
        cronjob: '>=2.3.0'
        project_manager_plus: '^1.5.0'
        yform: '>=3.4.2'
    redaxo: '^5.15'
    php:
        version: '>=8.0'

redaxo_versions:
