package: project_manager_plus/hosting
version: '1.0.8'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/project_manager_plus

page:
    title: 'translate:hosting_menu_entry'
    icon: rex-icon fa-server # Icon von Font Awesome
    perm: project_manager_plus_hosting[] 
    
pages:
    project_manager_plus/hosting/overview:
        title: translate:project_manager_plus_hosting_title
        
requires:
    packages:
        project_manager_plus: '^1.2.0'
        cronjob: '>=2.3.0'
        project_manager_plus/server: '>=1.3.8'        
