package: project_manager_plus/pagespeed
version: '1.2.4'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/project_manager_plus

page:
    title: 'translate:pagespeed_menu_entry'
    icon: rex-icon fa-tachometer # Icon von Font Awesome
    perm: project_manager_plus_pagespeed[] 
    
pages:
    project_manager_plus/pagespeed/overview:
        title: 'translate:project_manager_plus_pagespeed_title'
    project_manager_plus/pagespeed/config:
        title: 'translate:project_manager_plus_pagespeed_config'
        
requires:
    packages:
        project_manager_plus: '^1.0.0'
        cronjob: '>=2.3.0'
        project_manager_plus/server: '>=1.3.8'        
